CREATE DATABASE IF NOT EXISTS cc_authdb;
CREATE DATABASE IF NOT EXISTS cc_reservationdb;
CREATE DATABASE IF NOT EXISTS cc_salledb;
CREATE DATABASE IF NOT EXISTS cc_userdb;
CREATE DATABASE IF NOT EXISTS cc_salledb;
